### ISSUE TITLE
[help wanted] How to implement this lib's feature into other platforms, for example, WeChat miniApp?

### ISSUE THREAD

**Issue by LC0117** [thu-info-community/thu-info-lib#58]
I am trying to develop a WeChat mini-program with some features like ThuInfo. However, I ran into some problems when I try to use this lib. The output is as follow.
<img width="386" alt="1" src="https://user-images.githubusercontent.com/77481149/142342321-f19cb078-7312-4cff-a7a8-3a768b164162.png">
And my code to import this lib:
```js
const thuInfo = require('thu-info-lib')
```
I am wondering if the error is caused by my code or this lib.

**Comment by UNIDY2002** [comment]
I'm not familiar with WeChat mini-program, but I guess this issue is caused by the import syntax of the lib, which might be incompatible with the compiler of WeChat mini-program. Modifying the value of field `module` in `tsconfig.json` from `"esnext"` to `"CommonJS"` and then re-generating the lib with `yarn build` might help solve the problem.
I will test whether this modification maintains backward compatibility and consider making a new release recently.

**Comment by UNIDY2002** [comment]
Update: I've made a release using commonjs import syntax, and if you are still interested in integrating into miniApp, you can try `thu-info-lib@1.3.5` or `thu-info-lib@2.0.0-alpha.10` :)

**Comment by LC0117** [comment]
Danke! I’ll try it out when I get free.
